version: '3.7'


networks:
  backend:
    driver: bridge


volumes:
  main_db_data:
  var_tic_tac_toe:

services:
  main_db:
    build:
      context: .
      dockerfile: deploy/postgres/Dockerfile
      args:
        VERSION: ${POSTGRES_VERSION}
    networks:
      - backend
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_MAIN_NAME}
      POSTGRES_USER: ${POSTGRES_MAIN_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_MAIN_PASSWORD}
    volumes:
      - main_db_data:/var/lib/postgresql/data

  tic_tac_toe:
    build:
      context: tic_tac_toe
      dockerfile: ../deploy/Dockerfile
      target: prod
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - main_db
    ports:
      - 8080:8080
    volumes:
      - var_tic_tac_toe:/var/project
    command:
      /usr/local/bin/gunicorn  --bind 0.0.0.0:8080  tic_tac_toe.wsgi

  init:
    build:
      context: tic_tac_toe
      dockerfile: ../deploy/Dockerfile
      target: prod
    depends_on:
      - tic_tac_toe
      - main_db
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - var_tic_tac_toe:/var/project
    working_dir: /home/project/dist
    command:
      /home/projec/dist/manage.py migrate