# Generated by Django 3.1.3 on 2020-11-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="player",
            field=models.CharField(
                choices=[
                    ("X", "Player is X"),
                    ("O", "Player is O"),
                    ("NOBODY", "Player is Nobody"),
                ],
                default="NOBODY",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "The game is running!"),
                    ("X_WON", "Player X won the game!"),
                    ("O_WON", "Player O won the game!"),
                    ("DRAW", "The game is not active."),
                ],
                default="RUNNING",
                max_length=7,
            ),
        ),
    ]
